import type { DemoVaultItem } from "./types";

const d = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString();

/** Fictional demo vault — no real people, companies, or credentials. */
export const DEMO_VAULT_ITEMS: DemoVaultItem[] = [
  { id: "1", name: "GitHub", username: "alex.morgan@example.com", password: "Gh3nt!d3m0_2026#xK", website: "github.com", notes: "Org SSO enabled · 2FA required", category: "login", tag: "Work", favorite: true, createdAt: d(45), updatedAt: d(2), color: "from-slate-700 to-slate-900", icon: "github" },
  { id: "2", name: "Cloudflare", username: "ops@acme-corp.example", password: "CF_z0ne_Dns!9m", website: "dash.cloudflare.com", category: "login", tag: "Infra", favorite: false, createdAt: d(60), updatedAt: d(5), color: "from-orange-400 to-amber-600", icon: "globe" },
  { id: "3", name: "Stripe API Keys", username: "sk_test_••••4f2a", password: "sk_test_51Nx8k2L9pQ3mR7vW4yZ", website: "dashboard.stripe.com", notes: "Sandbox only", category: "secret", tag: "API", favorite: true, createdAt: d(90), updatedAt: d(12), color: "from-indigo-500 to-violet-600", icon: "credit-card" },
  { id: "4", name: "Staging SSH", username: "deploy@staging-eu-1", password: "ssh-ed25519 AAAA…demo", category: "secret", tag: "Server", favorite: false, createdAt: d(120), updatedAt: d(8), color: "from-emerald-500 to-teal-600", icon: "key" },
  { id: "5", name: "AWS Sandbox", username: "admin", password: "Aws!D3m0#9xK2mN8", website: "console.aws.amazon.com", category: "login", tag: "Cloud", favorite: true, createdAt: d(100), updatedAt: d(3), color: "from-amber-500 to-orange-600", icon: "cloud" },
  { id: "6", name: "Linode", username: "root", password: "L1n0d3_d3m0!p2", website: "cloud.linode.com", notes: "Demo app server", category: "login", tag: "Infra", favorite: false, createdAt: d(30), updatedAt: d(5), color: "from-sky-500 to-blue-600", icon: "server" },
  { id: "7", name: "Proton Mail", username: "jordan.lee@proton.me", password: "Pr0t0n_S3cur3!99", website: "mail.proton.me", category: "login", tag: "Personal", favorite: true, createdAt: d(200), updatedAt: d(1), color: "from-violet-600 to-indigo-700", icon: "mail" },
  { id: "8", name: "Google Workspace", username: "admin@acme-corp.example", password: "GW_admin!2026", website: "admin.google.com", category: "login", tag: "Work", favorite: false, createdAt: d(80), updatedAt: d(20), color: "from-blue-500 to-indigo-600", icon: "mail" },
  { id: "9", name: "Figma", username: "design@studio.example", password: "F1gm@_D3m0", website: "figma.com", category: "login", tag: "Work", favorite: false, createdAt: d(40), updatedAt: d(6), color: "from-fuchsia-500 to-purple-600", icon: "layout" },
  { id: "10", name: "Notion", username: "team@acme-corp.example", password: "N0t!0n_W0rksp", website: "notion.so", category: "login", tag: "Work", favorite: false, createdAt: d(40), updatedAt: d(6), color: "from-neutral-700 to-neutral-900", icon: "file-text" },
  { id: "11", name: "Slack", username: "alex.morgan@example.com", password: "Sl@ck_W0rk!88", website: "acme-corp.slack.com", category: "login", tag: "Work", favorite: false, createdAt: d(70), updatedAt: d(9), color: "from-fuchsia-500 to-purple-600", icon: "message-square" },
  { id: "12", name: "MongoDB Atlas", username: "cluster-admin", password: "M0ng0_Atl@s!demo", website: "cloud.mongodb.com", category: "secret", tag: "Database", favorite: true, createdAt: d(95), updatedAt: d(7), color: "from-green-600 to-emerald-700", icon: "database" },
  { id: "13", name: "Postgres Staging", username: "postgres", password: "Pg_Stg!xK9m2", notes: "Read replica on eu-west-1", category: "secret", tag: "Database", favorite: false, createdAt: d(110), updatedAt: d(15), color: "from-blue-600 to-cyan-700", icon: "database" },
  { id: "14", name: "Redis Cache", username: "default", password: "R3d!s_C4ch3_k3y", category: "secret", tag: "Infra", favorite: false, createdAt: d(50), updatedAt: d(11), color: "from-red-600 to-rose-700", icon: "database" },
  { id: "15", name: "Vercel", username: "deploy@studio.example", password: "V3rc3l_T0k3n!", website: "vercel.com", category: "login", tag: "DevOps", favorite: false, createdAt: d(35), updatedAt: d(4), color: "from-neutral-800 to-black", icon: "triangle" },
  { id: "16", name: "Datadog API", username: "api-key", password: "dd_api_8f2a9c1b3e5d", category: "secret", tag: "API", favorite: false, createdAt: d(65), updatedAt: d(18), color: "from-violet-600 to-indigo-700", icon: "activity" },
  { id: "17", name: "Legacy Vault Export", username: "migration", password: "M1gr@t!0n_2025", notes: "Archive after migration complete", category: "note", tag: "Archive", favorite: false, createdAt: d(150), updatedAt: d(60), color: "from-slate-500 to-slate-700", icon: "file-text" },
  { id: "18", name: "WiFi — Studio", username: "SSID: Acme-Studio-5G", password: "W1f1_D3m0_2026!", category: "note", tag: "Network", favorite: false, createdAt: d(25), updatedAt: d(25), color: "from-cyan-500 to-blue-600", icon: "wifi" },
  { id: "19", name: "Corporate Visa", username: "•••• 4242", password: "CVV 482 · Exp 09/28", notes: "Travel expenses only", category: "card", tag: "Finance", favorite: true, createdAt: d(180), updatedAt: d(30), color: "from-blue-700 to-indigo-800", icon: "credit-card" },
  { id: "20", name: "Personal Debit", username: "•••• 1005", password: "CVV 291 · Exp 03/27", category: "card", tag: "Personal", favorite: false, createdAt: d(200), updatedAt: d(45), color: "from-emerald-700 to-teal-800", icon: "credit-card" },
  { id: "21", name: "Linear", username: "jordan.lee@studio.example", password: "L1n3ar_D3m0!", website: "linear.app", category: "login", tag: "Work", favorite: false, createdAt: d(20), updatedAt: d(2), color: "from-indigo-500 to-violet-600", icon: "layout" },
  { id: "22", name: "OpenAI API", username: "org-demo", password: "sk-proj-8xK2mN9pQ3vW", category: "secret", tag: "API", favorite: false, createdAt: d(15), updatedAt: d(1), color: "from-neutral-900 to-neutral-700", icon: "sparkles" },
  { id: "23", name: "Recovery Codes", username: "2FA backup", password: "A1B2-C3D4-E5F6-G7H8", notes: "Store offline · printed copy in safe", category: "note", tag: "Security", favorite: true, createdAt: d(5), updatedAt: d(5), color: "from-amber-600 to-orange-700", icon: "key-round" },
  { id: "24", name: "Spotify", username: "jordan.lee@example.com", password: "Sp0t!fy_D3m0", website: "spotify.com", category: "login", tag: "Personal", favorite: false, createdAt: d(88), updatedAt: d(22), color: "from-green-500 to-emerald-600", icon: "activity" },
  { id: "25", name: "Netflix", username: "family@home.example", password: "N3tfl!x_D3m0", website: "netflix.com", category: "login", tag: "Personal", favorite: false, createdAt: d(120), updatedAt: d(40), color: "from-red-600 to-rose-700", icon: "globe" },
];
