#!/usr/bin/env node
/**
 * NovaSafe landing — SEO asset generator.
 *
 * Writes `public/sitemap.xml` and `public/robots.txt` from the canonical
 * route list in `scripts/seo-routes.mjs`. Runs as a pure Node ESM script
 * (no TS, no extra deps) so it works in:
 *
 *   - local dev (`pnpm seo:generate`)
 *   - `pnpm build` (auto-invoked via the `prebuild` npm lifecycle hook)
 *   - Docker builds (the Dockerfile sets VITE_LANDING_URL before `pnpm build`)
 *   - GitHub Actions (env reaches the build container as ENV in Dockerfile)
 *
 * The site origin is resolved from env (in priority order):
 *
 *   PUBLIC_SITE_URL  >  VITE_LANDING_URL  >  https://novasafe.io
 *
 * That order means CI/CD can override per-environment without touching
 * source, but every code path has a safe production default.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { seoRoutes } from "./seo-routes.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const publicDir = resolve(projectRoot, "public");

const DEFAULT_PROD_ORIGIN = "https://novasafe.io";

/** Strip trailing slash so we never emit `https://example.com//foo`. */
function normaliseOrigin(raw) {
  const trimmed = (raw ?? "").trim();
  if (!trimmed) return null;
  try {
    const url = new URL(trimmed);
    return `${url.protocol}//${url.host}`;
  } catch {
    return null;
  }
}

function resolveOrigin() {
  const candidates = [
    ["PUBLIC_SITE_URL",  process.env.PUBLIC_SITE_URL],
    ["VITE_LANDING_URL", process.env.VITE_LANDING_URL],
  ];
  for (const [name, value] of candidates) {
    const normalised = normaliseOrigin(value);
    if (normalised) {
      return { origin: normalised, source: name };
    }
  }
  return { origin: DEFAULT_PROD_ORIGIN, source: "default(novasafe.io)" };
}

/** Conservative XML attribute escaper for `<loc>` values. */
function xmlEscape(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function buildSitemapXml(origin, lastmod) {
  const lines = [];
  lines.push(`<?xml version="1.0" encoding="UTF-8"?>`);
  lines.push(
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
  );

  for (const route of seoRoutes) {
    const url = new URL(route.path, origin).toString();
    lines.push(`  <url>`);
    lines.push(`    <loc>${xmlEscape(url)}</loc>`);
    lines.push(`    <lastmod>${lastmod}</lastmod>`);
    lines.push(`    <changefreq>${route.changefreq}</changefreq>`);
    lines.push(`    <priority>${route.priority.toFixed(1)}</priority>`);
    lines.push(`  </url>`);
  }

  lines.push(`</urlset>`);
  return lines.join("\n") + "\n";
}

function buildRobotsTxt(origin) {
  // Indexable + every well-known bot explicitly named so future
  // tightening (e.g. blocking AI crawlers) is a one-line diff.
  return [
    `# NovaSafe — robots policy`,
    `# Generated by scripts/generate-seo.mjs. Do not edit by hand.`,
    ``,
    `User-agent: Googlebot`,
    `Allow: /`,
    ``,
    `User-agent: Bingbot`,
    `Allow: /`,
    ``,
    `User-agent: Twitterbot`,
    `Allow: /`,
    ``,
    `User-agent: facebookexternalhit`,
    `Allow: /`,
    ``,
    `User-agent: *`,
    `Allow: /`,
    ``,
    `Sitemap: ${origin}/sitemap.xml`,
    ``,
  ].join("\n");
}

function main() {
  const { origin, source } = resolveOrigin();
  const lastmod = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

  mkdirSync(publicDir, { recursive: true });

  const sitemapPath = resolve(publicDir, "sitemap.xml");
  const robotsPath = resolve(publicDir, "robots.txt");

  writeFileSync(sitemapPath, buildSitemapXml(origin, lastmod), "utf8");
  writeFileSync(robotsPath, buildRobotsTxt(origin), "utf8");

  const relSitemap = sitemapPath.replace(projectRoot + "/", "");
  const relRobots = robotsPath.replace(projectRoot + "/", "");

  console.log(`[seo] origin = ${origin}  (from ${source})`);
  console.log(`[seo] wrote  ${relSitemap}  (${seoRoutes.length} urls, lastmod=${lastmod})`);
  console.log(`[seo] wrote  ${relRobots}`);
}

try {
  main();
} catch (err) {
  console.error("[seo] generation failed:", err);
  process.exit(1);
}
