// Auto-generated by scripts/generate-journal-posts.mjs — do not edit by hand.
export type JournalPost = {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  readingTimeMinutes: number;
};

export const FALLBACK_JOURNAL_POSTS: JournalPost[] = [
  {
    slug: "why-most-password-managers-still-require-trust",
    category: "Security",
    title: "Why Most Password Managers Still Require Trust",
    excerpt: "Most password managers ask you to trust their servers. NovaSafe is built on zero-knowledge security so your vault stays private — even from us.",
    readingTimeMinutes: 6,
  },
  {
    slug: "passwords-vs-passkeys-whats-actually-safer",
    category: "Research",
    title: "Passwords vs Passkeys: What's Actually Safer?",
    excerpt: "Passkeys reduce phishing and credential theft, but migration matters. A practical look at when passkeys win and how to adopt them safely.",
    readingTimeMinutes: 5,
  },
  {
    slug: "understanding-zero-knowledge-security",
    category: "Engineering",
    title: "Understanding Zero-Knowledge Security",
    excerpt: "How encryption happens on your device before data ever reaches the cloud — and why that architecture is the foundation of modern password security.",
    readingTimeMinutes: 7,
  }
];

/** Latest published posts — embedded at build time for SEO/crawlers. */
export const JOURNAL_POSTS: JournalPost[] = [
  {
    slug: "why-most-password-managers-still-require-trust",
    category: "Security",
    title: "Why Most Password Managers Still Require Trust — And How NovaSafe Is Different",
    excerpt: "Most password managers promise security, but they still require users to trust the provider. Learn how NovaSafe approaches password management with privacy, encryption, and zero-knowledge principles at its core.",
    readingTimeMinutes: 3,
  },
  {
    slug: "passwords-vs-passkeys-whats-actually-safer",
    category: "Research",
    title: "Passwords vs Passkeys: What's Actually Safer?",
    excerpt: "Passkeys reduce phishing and credential theft, but migration matters. A practical look at when passkeys win and how to adopt them safely.",
    readingTimeMinutes: 5,
  },
  {
    slug: "understanding-zero-knowledge-security",
    category: "Engineering",
    title: "Understanding Zero-Knowledge Security",
    excerpt: "How encryption happens on your device before data ever reaches the cloud — and why that architecture is the foundation of modern password security.",
    readingTimeMinutes: 7,
  }
];
