name: Ticket automation

on:
  issues:
    types: [labeled]

jobs:
  start-ticket:
    if: github.event.label.name == 'status:in-progress'
    uses: novasafe-org/novasafe-deployment/.github/workflows/ticket-create-branch.yml@master
    with:
      issue_number: ${{ github.event.issue.number }}
    secrets: inherit
